Models/Repositories/Section.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ResearchData.Models.EF
{   
    public class Section
    {
        [Key]
        public int SectionID { get; set; }

        [Required(ErrorMessage ="Please enter a Section Name")]
        public string SectionName { get; set; }
      
        /* Relationship
           FKs         
        */
     
        /* Ref. by */    
        public virtual ICollection<Subsection> Subsection { get; set; }

    }
}

Models/ViewModels/SectionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;  
using ResearchData.Models;
using ResearchData.Models.EF;

namespace ResearchData.Models
{
    public class SectionViewModel: BaseViewModel
    {
        public Section Section {get;set;}
        public IEnumerable<Section> Sections {get;set;}
        public QuestionType QuestionType{get;set;}       
        public IEnumerable<QuestionType> QuestionTypes{get;set;}
        public Subsection Subsection {get;set;}
        public IEnumerable<Subsection> Subsections {get;set;}
       
    }
}

Components/AddSecViewComponent.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ResearchData.Components
{
    public class AddSecViewComponent: ViewComponent
    {        
        public IViewComponentResult Invoke()
        {           
            return View();
        }
    }
}

Components/AddSubSecViewComponent.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ResearchData.Components
{
    public class AddSubSecViewComponent: ViewComponent
    {        
        public IViewComponentResult Invoke()
        {           
            return View();
        }
    }
}

Controllers/SectionController.cs
using ResearchData.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

using ResearchData.Models.Interfaces;
using ResearchData.Models.EF;

using System.Data.Odbc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace ResearchData.Controllers
{
   
    public class SectionController : Controller
    {
        //Private Fields
        //--------------

        private ISection context;
        private ISubsection subs_ctx;
        private IQuestionType qtypes_ctx;  
        private IAccount acc_context;
        private IConfiguration Configuration;
        
        public string strConn = @"Server=156.38.224.15;Database=KisCret_DB;MultipleActiveResultSets=true;User ID=xslicwih_ms_admin;password=#21MsDBUser@"; 
        //public string sOffCampuServer = @"Server=196.255.240.74;Database=iinfo;MultipleActiveResultSets=true;User ID=Sthembiso;password=IIS123";

        // public string sCampusServer = Configuration.GetConnectionString("Data:ResearchData:ConnectionString");
        // public string sOffCampuServer = Configuration.GetConnectionString("Data:ResearchData2:ConnectionString");
        
              
        //Constructor
        //-----------
        public SectionController(ISection ctx_, ISubsection subs_ctx_, IQuestionType qtypes_ctx_, IAccount acc_context_, IConfiguration configuration)
        {
            context = ctx_;
            subs_ctx = subs_ctx_;
            qtypes_ctx = qtypes_ctx_;
            acc_context = acc_context_;
            this.Configuration = configuration;
        }

        //READ
        // public ViewResult Index() => View(context.Sections);
        public ViewResult Index() 
        {                      
            SubsectionViewModel model = new SubsectionViewModel();
            model.Sections = context.Sections;
            model.Accounts = acc_context.Accounts;

            //model.QuestionTypes = qtypes_ctx.QuestionTypes;          
            return View(model);

            //  SubsectionViewModel vm = new SubsectionViewModel
            // {
            //     SelectSections = getSections()
            // };

            // return View(vm);
        }

        //CREATE
        [HttpGet]
        public ViewResult Add() 
        {
            SectionViewModel model = new SectionViewModel();         
            model.Accounts = acc_context.Accounts;

            return View(model);
        }

        [HttpPost]
        public IActionResult Add(Section Section)
        {
            if(ModelState.IsValid)
            {
                context.SaveSection(Section);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }
        
        //UPDATE
        public ViewResult Edit(int SectionID)
        {
            SectionViewModel vm = new SectionViewModel();
           
            Section Section = context.Sections.FirstOrDefault(c => c.SectionID == SectionID);
        
            vm.Section.SectionName =  Section.SectionName;
            vm.Accounts = acc_context.Accounts;
             
            return View(vm);

        }
                  

        [HttpPost]
        public IActionResult Edit(SubsectionViewModel vm)
        {
            Section Section = context.Sections.FirstOrDefault(c => c.SectionID == vm.Section.SectionID);

             if(Section != default(Section))
            {
                Section.SectionName = vm.Section.SectionName;                                                
            }

            if(ModelState.IsValid)
            {
                context.SaveSection(Section);
                return RedirectToAction("Index");
            }
            else
            {
                return View(Section);
            }
        }

        //DELETE
        public IActionResult Delete(int SectionID)
        {
            Section Section = context.DeleteSection(SectionID);

            if(Section != null)
            {               
                TempData["message"] = $"{Section.SectionName} was deleted";
            }

            return RedirectToAction("Index");
        }       
        
        public ViewResult SectionList() => View(context.Sections);
        
          public Microsoft.AspNetCore.Mvc.Rendering.SelectList getSections()
        {
            List<Section> models = new List<Section>();
                       
            using(SqlConnection connection = new SqlConnection(strConn)) 
            {
                using(SqlCommand cmd = new SqlCommand("", connection))
                {
                    connection.Open();
                    cmd.CommandText = "Select SectionName, SectionID from [Section]";
                    using(var reader = cmd.ExecuteReader())
                    {
                        if(reader.HasRows)
                        {
                            while(reader.Read())
                            {
                                var m = new Section();
                                m.SectionID = reader.GetInt32(reader.GetOrdinal("SectionID"));
                                m.SectionName = reader.GetString(reader.GetOrdinal("SectionName"));
                                models.Add(m);
                            }
                        }
                    }
                }
            };

            Microsoft.AspNetCore.Mvc.Rendering.SelectList SectionSelect = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(models, "SectionID", "SectionName");
            return SectionSelect;
        }
    
        
    }
}

Views/Section/Index.cshtml
@model SubsectionViewModel
@{
     ViewData["Title"] = "Question Sections";
    Layout = "_dashLayout";
}

<div class="text-center"> 

    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        <h1>Manage Survey Questions & Sections</h1>
                        <hr />
                    </div>
                </div>
            </div>
   
                <div class="form-group text-right">
                    <span><button type="submit" onclick="AddSec()" class="btn btn-outline-info">Add Section</button></span>
                     <span>
                          <a href="~/Subsection/Index" class="btn btn-outline-info">Manage Sub-Section</a>
                          @* <button type="submit" onclick="AddSubSec()" class="btn btn-outline-info">Add Sub-Section</button> *@
                    </span>
                    <hr />
                    
                </div>

                <div class="col-sm-12 col-md-8 col-lg-8" id="id_AddSec" style="display:none;">
                    <h5 class="text-center">Question Section Name</h5>
                    <hr /><br />
                     @await Component.InvokeAsync("AddSec")                         
                </div>

                <div class="col-sm-12 col-md-8 col-lg-8" id="id_AddSubSec" style="display:none;">
                    <h5 class="text-center">Question Sub-Section Name</h5>
                    <hr /><br />
                     @* @await Component.InvokeAsync("AddSubSec")                          *@
                </div>
                    
                <table class="table table-striped table-bordered table-sm">
                    <tr>                                                          
                        <th class="text-center">Question Section Name</th> 
                    </tr>
                 @{
                    foreach (var item in Model.Sections)
                    {
                        <tr>                          
                            <td class="text-center">@item.SectionName</td>                           
                            <td class="text-center">
                                <form asp-action="Delete" method="Post">
                                    <a asp-action="Edit" class="btn btn-outline-warning btn-sm" asp-route-SectionID="@item.SectionID">
                                        Edit
                                    </a>
                                    <button type="submit" type="submit" class="btn btn-danger btn-sm">
                                        Delete
                                    </button>
                                </form> 
                            </td>
                            <td>
                                
                                
                            </td>

                        </tr>
                    }
                }
                </table>

                
        </div>
    </div>
</div>

<script type="text/javascript">
    function AddSec() {
        var x = document.getElementById("id_AddSec");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }

    function AddSubSec() {
        var x = document.getElementById("id_AddSubSec");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
</script>