Models/ViewModels/QuestionTypeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;  
using ResearchData.Models;
using ResearchData.Models.EF;


namespace ResearchData.Models
{
    public class QuestionTypeViewModel: BaseViewModel
    {
        public QuestionType QuestionType{get;set;}       
        public IEnumerable<QuestionType> QuestionTypes{get;set;}
        public int QuestionTypeID {get;set;}
        public string QuestionTypeName {get;set;}
        
    }
}

Components/AddQTypeViewComponent.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ResearchData.Components
{
    public class AddQTypeViewComponent: ViewComponent
    {        
        public IViewComponentResult Invoke()
        {           
            return View();
        }
    }
}

Controllers/QuestionTypeController.cs
using ResearchData.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

using ResearchData.Models.Interfaces;
using ResearchData.Models.EF;
using Microsoft.Extensions.Configuration;

namespace ResearchData.Controllers
{
   
    public class QuestionTypeController : Controller
    {
        //Private Fields
        //--------------

        private IQuestionType context;
        private IAccount acc_context;
        private IConfiguration Configuration;

        //Constructor
        //-----------
        public QuestionTypeController(IQuestionType ctx, IAccount acc_context_, IConfiguration configuration)
        {
            context = ctx;
            acc_context = acc_context_;
            this.Configuration = configuration;
        }

        //READ
        public ViewResult Index()
        {            
            QuestionTypeViewModel model = new QuestionTypeViewModel();
            model.QuestionTypes = context.QuestionTypes;
            model.Accounts = acc_context.Accounts;
            return View(model);

            //ProfileViewModel vm = new ProfileViewModel();
            // vm.Subunits = sec_context.Subunits;
            // return(vm);
        }
        // public ViewResult Index() => View();

        //CREATE
        [HttpGet]
        public ViewResult Add()
        {
            QuestionTypeViewModel vm = new QuestionTypeViewModel();
            vm.QuestionType = new QuestionType();
            vm.Accounts = acc_context.Accounts;

            return View(vm);
        }

        [HttpPost]
        public IActionResult Add(QuestionTypeViewModel vm)
        {
            var QuestionType = new QuestionType
            {
                QuestionTypeName = vm.QuestionType.QuestionTypeName                
            };


            if(ModelState.IsValid)
            {
                context.SaveQuestionType(QuestionType);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }
        
        //UPDATE
        public ViewResult Edit(int QuestionTypeID)
        {
            QuestionTypeViewModel vm = new QuestionTypeViewModel();
            vm.Accounts = acc_context.Accounts;

            QuestionType QuestionType = context.QuestionTypes.FirstOrDefault(c => c.QuestionTypeID == QuestionTypeID);
        
            vm.QuestionTypeName =  QuestionType.QuestionTypeName;
                      
            return View(vm);             
        }   

        [HttpPost]
        public IActionResult Edit(QuestionTypeViewModel vm)
        {
            QuestionType QuestionType = context.QuestionTypes.FirstOrDefault(c => c.QuestionTypeID == vm.QuestionTypeID);

             if(QuestionType != default(QuestionType))
            {
                QuestionType.QuestionTypeName = vm.QuestionTypeName;                                               
            }


            if(ModelState.IsValid)
            {
                context.SaveQuestionType(QuestionType);
                return RedirectToAction("Index");
            }
            else
            {
                return View(QuestionType);
            }
        }


        //DELETE
        public IActionResult Delete(int QuestionTypeID)
        {
            QuestionType QuestionType = context.DeleteQuestionType(QuestionTypeID);

            if(QuestionType != null)
            {               
                TempData["message"] = $"{QuestionType.QuestionTypeName} was deleted";
            }

            return RedirectToAction("Index");
        }       
        
         public ViewResult QuestionTypeList() => View(context.QuestionTypes);
        

        
    }
}

Views/QuestionType/Edit.cshtml
@model QuestionTypeViewModel

@{
    ViewData["Title"] = "Edit Q.. Type";
    Layout = "_dashLayout";
}

<div class="text-center"> 

    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        <h1>Edit Questions Types</h1>
                        <hr />
                    </div>
                </div>
            </div>        
                <form asp-action="Edit" method="post" class="text-center">

                    <div asp-validation-summary="All"></div>

                    <div class="container-fluid">                                                      
                        <div class="row">
                            <div class="col-sm-12 col-md-8 col-lg-8" style="margin: 0 auto; float: none;">
                            
                                <input asp-for="QuestionTypeID" type="hidden" class="form-control" />

                                <div class="form-group">
                                    <label asp-for="QuestionTypeName"></label>
                                    <div><span asp-validation-for="QuestionTypeName" class="text-danger"></span></div>
                                    <input asp-for="QuestionTypeName" class="form-control" />
                                </div>
                            
                                <div class="form-group">
                                    <div class="text-center">
                                        <button class="btn btn-primary" type="submit">Save</button>
                                        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </form>   
           
        </div>
    </div>
</div>

Views/QuestionType/Index.cshtml
@model QuestionTypeViewModel
@{
     ViewData["Title"] = "Question Type";
    Layout = "_dashLayout";
}

<div class="text-center"> 

    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        <h1>Manage Survey Questions Types</h1>
                        <hr />
                    </div>
                </div>
            </div>
   
                <div class="form-group text-right">
                    <span><a href="~/Question/Index" class="btn btn-outline-primary">Manage Questions</a></span>
                    <span><button type="submit" onclick="AddQType()" class="btn btn-outline-info">Add New Question Type</button></span>
                    <hr />                    
                </div>
                    
                <table class="table table-striped table-condensed table-bordered">
                    <tr>                                                          
                        <th>Question Type</th>
                        <th>Question Type ID</th>
                        <th class="text-info h5">Action</th> 
                    </tr>
                    
                        @{
                            foreach(var item in Model.QuestionTypes)
                            {
                                <tr>
                                <td>@item.QuestionTypeName</td>
                                <td>@item.QuestionTypeID</td>
                              
                                <td class="text-center">
                                    <form asp-action="Delete" method="post">
                                        <a asp-action="Edit" class="btn btn-sm btn-warning" asp-route-QuestionTypeID="@item.QuestionTypeID">
                                            Edit
                                        </a>
                                        <input type="hidden" name="QuestionTypeID" value="@item.QuestionTypeID" />
                                        <button type="submit" class="btn btn-danger btn-sm">
                                            Delete
                                        </button>
                                    </form>
                                </td>
                                </tr>
                            }
                        }
                    
                </table>

                <hr />
                <div class="row column1">
                  
                        <div class="col-sm-12 col-md-12 col-lg-12" id="id_AddQType" style="display:none;">                       
                            @await Component.InvokeAsync("AddQType")                        
                        </div>
                   
                </div>
                
        </div>
    </div>
</div>



<script type="text/javascript">
    function AddQType() {
        var x = document.getElementById("id_AddQType");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }    
</script>