Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ResearchData.Models;

using ResearchData.Models.Interfaces;
using System.ComponentModel;


namespace ResearchData.Controllers
{   
    // [Authorize (Roles="Admins")]
    public class UserAccountController : Controller
    {
        //private properties
        private UserManager<User> UserManager;
        private SignInManager<User> signInManager;
     
        //Const
        public UserAccountController(UserManager<User> userManager_, SignInManager<User> signInManager_)
        {
            UserManager = userManager_;
            signInManager = signInManager_;          
        }

        //Action Methods      
        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            return View(new LoginModel {ReturnUrl = returnUrl } );
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel loginModel, string ReturnUrl)
        {
            if(ModelState.IsValid)
            {
                User user = await UserManager.FindByEmailAsync(loginModel.Email);

                if(user != null)
                {
                    //await signInManager.SignOutAsync();

                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, loginModel.Password, false, false);

                    if(result.Succeeded)
                    {
                        return Redirect(ReturnUrl ?? "/Home/About");
                    }
                    else
                        return Redirect(ReturnUrl ?? "/UserAccount/Login");
                }

                ModelState.AddModelError(nameof(LoginModel.Email), "Invalid username or password");
            }

            ModelState.AddModelError(nameof(LoginModel.Email), "Invalid username or password");
            return View(loginModel);

        }

        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }

       

    }
}

Views/UserAccount/AccessDenied.cshtml
@{
    ViewData["Title"] = "Access Denied";
    Layout = "_Layout";
}



<div class="text-center">
    <h1 class="display-4">Research Data Management</h1>   
    <hr />

    <div class="bg-danger mb-1 p-2 text-white">
        Access Denied
    </div>
    <a asp-action="Index" asp-controller="Home" class="btn btn-primary">
        Return to Homepage
    </a>
</div>

Views/UserAccount/Login.cshtml
@model LoginModel
@{
    Layout="";
    ViewData["Title"] = "Login";
}

<!DOCTYPE html>
<html lang="en">
    <head>
         <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- site icon -->
      <link rel="icon" href="~/images/fevicon.png" type="image/png" />
      <!-- bootstrap css -->
      <link rel="stylesheet" href="~/css/bootstrap.min.css" />
      <!-- site css -->
      <link rel="stylesheet" href="~/css/style.css" />
      <!-- responsive css -->
      <link rel="stylesheet" href="~/css/responsive.css" />
      <!-- color css -->
      <link rel="stylesheet" href="~/css/colors.css" />
      <!-- select bootstrap -->
      <link rel="stylesheet" href="~/css/bootstrap-select.css" />
      <!-- scrollbar css -->
      <link rel="stylesheet" href="~/css/perfect-scrollbar.css" />
      <!-- custom css -->
      <link rel="stylesheet" href="~/css/custom.css" />
      <link rel="stylesheet" href="~/css/font-awesome.min.css" />

      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" />
    </head>
    <body class="inner_page login">
       
        <div class="full_container">
            <div class="container">
                <div class="center verticle_center full_height">
                <div class="login_section">
                    <div class="logo_login">
                        <div class="center">
                            <div class="row">
                                <div class="col-sm-6">
                                    <img width="210" style="max-width:100%;" src="~/images/logo/logo.png" class="img-responsive" alt="#" />
                                </div>
                                <div class="col-sm-6 mt-4">
                                    <h4 style="color: #ccc; ">Research Data</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="login_form">
                        <form asp-action="Login" asp-controller="UserAccount" method="post">

                            <div class="row">
                                <div class="col-sm-6 text-danger text-center center" style="margin: 0 auto; float: none;">
                                    <span asp-validation-for="Email"></span>
                                    <span asp-validation-for="Password"></span>
                                    <hr />
                                </div>
                            </div>
                            
                            <input type="hidden" asp-for="ReturnUrl" />
                            <h3 class="h3">Login</h3> 

                            <fieldset>
                                <div class="field">                                        
                                        <label asp-for="Email" class="label_field">
                                            Email Address 
                                        </label>                                        
                                        <input asp-for="Email" type="email"  name="email" placeholder="E-mail" />
                                </div>
                                <div class="field">

                                        <label  asp-for="Password" class="label_field">
                                            Password </span>
                                        </label>                                        
                                        <input  asp-for="Password" type="password" name="password" placeholder="Password" />
                                </div>
                                <div class="field">
                                    <label class="label_field hidden">hidden label</label>
                                    <label class="form-check-label"><input type="checkbox" class="form-check-input"> Remember Me</label>
                                    <a class="forgot" href="#">Forgotten Password?</a>
                                </div>
                                <div class="field margin_0 form-group">
                                    <label class="label_field hidden">hidden label</label>
                                    <button class="btn btn-primary" type="submit">Sing In</button>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
                </div>
            </div>
        </div>
   

         <!-- jQuery -->
      <script src="~/js/jquery.min.js"></script>
      <script src="~/js/popper.min.js"></script>
      <script src="~/js/bootstrap.min.js"></script>
      <!-- wow animation -->
      <script src="~/js/animate.js"></script>
      <!-- select country -->
      <script src="~/js/bootstrap-select.js"></script>
      <!-- owl carousel -->
      <script src="~/js/owl.carousel.js"></script> 
      <!-- chart js -->
      <script src="~/js/Chart.min.js"></script>
      <script src="~/js/Chart.bundle.min.js"></script>
      <script src="~/js/utils.js"></script>
      <script src="~/js/analyser.js"></script>
      <!-- nice scrollbar -->
      <script src="~/js/perfect-scrollbar.min.js"></script>
      <script>
         var ps = new PerfectScrollbar('#sidebar');
      </script>
      <!-- custom js -->
      <script src="~/js/custom.js"></script>
      <script src="~/js/chart_custom_style1.js"></script>

      <script src="~/js/site.js" asp-append-version="true"></script>
      
    </body>
 </html>
 

Views/UserAccount/Settings.cshtml
@model BaseViewModel

@{
     ViewData["Title"] = "Contact";
    Layout = "_dashLayout";
}

<div class="text-center"> 

     <div class="midde_cont">
                  <div class="container-fluid">
                     <div class="row column_title">
                        <div class="col-md-12">
                           <div class="page_title">
                              <h1>Settings</h1>
                              <hr />
                           </div>
                        </div>
                     </div>
                     <!-- row -->
                     <div class="row column1">
                        <div class="col-md-12">
                           <div class="white_shd full margin_bottom_30">
                              <div class="full graph_head">
                                 <div class="heading1 margin_0">
                                    <h2>Settings</h2>
                                 </div>
                              </div>
                              <div class="full price_table padding_infor_info">
                                 <div class="row">
                                    <!-- column contact --> 
                                    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 profile_details margin_bottom_30">
                                       <div class="contact_blog">
                                          <h4 class="brief">Survey Settings</h4>
                                          <div class="contact_inner">
                                            
                                              
                                            
                                          </div>
                                       </div>
                                    </div>
                                    <!-- end column contact blog -->
                                    <!-- column contact --> 
                                    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 profile_details margin_bottom_30">
                                       <div class="contact_blog">
                                          <h4 class="brief">User Settings</h4>
                                          <div class="contact_inner">
                                             
                                                                                
                                          </div>
                                       </div>
                                    </div>

                                     <!-- column contact --> 
                                    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 profile_details margin_bottom_30">
                                       <div class="contact_blog">
                                          <h4 class="brief">Questionnaire Settings</h4>
                                          <div class="contact_inner">                                             
                                                <h3>Create Layout for online Surveys</h3>
                                                <p>Get your data directly and monitor surveys</p>
                                                <p><strong>NOTE:</strong> Requires admin access to evasys for custom integration.</p>

                                          </div>
                                       </div>
                                    </div>
                                   
                                 </div>
                              </div>
                           </div>
                        </div>
                        <!-- end row -->
                     </div>
                     <!-- footer -->
                     <div class="container-fluid">
                        <div class="row">
                           <div class="footer">
                              <p>Department of Computer Science Copyright - @System.DateTime.Now.Year. All rights reserved.</p>
                                <p>
                                    &copy;DIRAP - IIS - UFS - <span><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></span>
                                </p>
                           </div>
                        </div>
                     </div>
                  </div>
                  <!-- end dashboard inner -->
               </div>

  
</div>